[build]
  publish = "build/"

[[redirects]]
  from = "/api/*"
  to = "https://stats.foldingathome.org/api/:splat"
  status = 200
  force = true

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"